theme: jekyll-theme-minimal
title: Strona Jana Krysta
description: Dodaj tę stronę do zakładek, aby być na bieżąco z aktualizacjami mojego projektu!
---
---

Witaj na mojej stronie

{% assign date = '2020-04-13T10:20:00Z' %}

- Original date - {{ date }}
- With timeago filter - {{ date | timeago }}
